vuex-options/package.json, vuex-options/src/defaults/endpoints.ts, vuex-options/src/defaults/indexers.ts, vuex-options/src/defaults/prefixes.ts
[update moonriver vuex-options](https://github.com/kodadot/nft-gallery/issues/3177#issuecomment-1159675810)
=> update moonriver vuex-options

uniquery/README.md
Structured the directions based on how I set it up on my local env on a new computer!
=> DRAFT: Development Changes

metasquid/.editorconfig, metasquid/.eslintignore, metasquid/.eslintrc, metasquid/.github/workflows/ci.yml, metasquid/.gitignore, metasquid/LICENSE, metasquid/README.md, metasquid/justfile, metasquid/package.json, metasquid/pnpm-lock.yaml, metasquid/renovate.json, metasquid/src/consolidator.ts, metasquid/src/entity.ts, metasquid/src/index.ts, metasquid/src/logger.ts, metasquid/src/serializer.ts, metasquid/src/shared.ts, metasquid/src/specific.ts, metasquid/src/types.ts, metasquid/test/index.test.ts, metasquid/tsconfig.json
[@kodadot1/metasquid](https://www.npmjs.com/package/@kodadot1/metasquid)
=> Subsqid utils

vuex-options/justfile, vuex-options/package.json, vuex-options/pnpm-lock.yaml, vuex-options/src/defaults/endpoints.ts, vuex-options/src/defaults/indexers.ts, vuex-options/src/defaults/prefixes.ts
- :robot: update deps just updates @polkadot
- :top: update packages
- :zap: cleanup prefixes
- :broom: less endpoints, smaller package
- :zap: new indexeers
- :robot: most legit justfile
- :bookmark: vuex-options@0.0.2
- :facepalm: forgot to make proper release
- :facepalm: forgot to make proper release
=> Moonriver in options

metasquid/build.config.ts, metasquid/package.json, metasquid/tsconfig.json
- :wrench: build config
- :bookmark: metasquid@0.0.1-rc.1
- :wrench: minimal node engine version
=> real slim squid

minipfs/README.md, minipfs/package.json, minipfs/src/gateways.ts, minipfs/src/magic.ts, minipfs/src/sanitize.ts, minipfs/test/purify.test.ts
- :zap: utilities for proper uri
- :bug: sanitize will throw on bad URO
- :tada: $purify
- :bookmark: minipfs@0.0.1-rc.1
Added `$purify` for sanitizing URIs
=> Purify for IPFS

metasquid/consolidator.d.ts, metasquid/entity.d.ts, metasquid/package.json, metasquid/types.d.ts
=> :wrench: TS compatible subpath imports

minipfs/package.json, minipfs/src/gateways.ts
=> fix: adjust default gateway with dedicated

sub-api/package.json, sub-api/pnpm-lock.yaml
=> chore: bump @polkadot

uniquery/src/rest/indexers.ts, uniquery/test/index.test.ts, vuex-options/src/defaults/indexers.ts
New rubick release `https://squid.subsquid.io/rubick/v/008/graphql`
ref kodadot/rubick#163
=> ✨ rubick 008 release

sub-api/package.json, sub-api/pnpm-lock.yaml
=> ⬆️ upgrade sub-api dependencies

minipfs/package.json, minipfs/src/gateways.ts
=> Koda Image in minipfs

metasquid/package.json, metasquid/pnpm-lock.yaml, metasquid/src/entity.ts, metasquid/src/shared.ts, metasquid/src/specific.ts, metasquid/src/types.ts, metasquid/test/index.test.ts
- :zap: simplier typeorm
- :zap: get base data from block
- :zap: toBaseBlock
- :zap: find by Id List
- :zap: toMap
- :zap: findByIdListAsMap
- :arrow_up: deps
- :broom: cleanup
- :test_tube: dummy test filler
=> this is how i squid

vuex-options/src/defaults/prefixes.ts
=> fix: rename rmrk

metasquid/build.config.ts, metasquid/logger.d.ts, metasquid/package.json, metasquid/pnpm-lock.yaml, metasquid/src/logger.ts
- :heavy_plus_sign: @subsquid/logger
- :tada: subsquid-based logger
- :wrench: build tools
- :bookmark: metasquid@0.1.3-rc.0
=> Logger for SubSquid

minipfs/package.json, minipfs/src/gateways.ts, minipfs/src/magic.ts, minipfs/src/obtain.ts
I found out that obtain safe is not safe :)
=> :zap: using [safe] function is not safe

README.md
=> 🏷️ add badges

.gitignore, minipfs/src/obtain.ts
related with #107 
Don't really know what's the scope behind this but here's the code
=> 🔧 obtain mode no-cors

.github/workflows/deploy.yml
=> :wrench: add posiblility to manually deploy package

metasquid/package.json, metasquid/src/entity.ts
- :zap: get entity and join fields
- :bookmark: metasquid@0.1.4-rc.0
=> one with join

socket.yml
Socket config to remove annoying defaults
https://docs.socket.dev/docs/socket-yml
=> :wrench: socket.dev config

minimark/package.json, minimark/src/rmrk/v2/helper.ts, minimark/src/rmrk/v2/types.ts
- :label: EquippableOption
- :zap: resolve behaviour of Equippable property
- :bookmark: minimark@0.1.5-rc.2
Feature for https://github.com/rmrk-team/rmrk-spec/blob/master/standards/rmrk2.0.0/interactions/equippable.md
=> Minimark: Equippable mastery

minimark/build.config.ts, minimark/common.d.ts, minimark/package.json
- :wrench: add common to build
- :wrench: common as submodule
- :wrench: common available in typescript
- :bookmark: minimark@0.1.6-rc.0
=> common minimark

minimark/package.json, minimark/src/rmrk/v2/identification.ts
- :zap: util to create theme id
- :bookmark: minimark@0.1.6-rc.1
themeId util
=> Minimark: ThemeID

minimark/src/rmrk/v2/create.ts, minimark/src/rmrk/v2/types.ts
=> feat: Add createMultipleItem

minimark/package.json, minimark/src/rmrk/v2/types.ts
=> :wrench: fix lint config

vuex-options/package.json, vuex-options/src/defaults/endpoints.ts
- :wrench: config of new RPC nodes
- :bookmark: vuex-options@0.1.2-rc.0
=> New default KSM nodes

minimark/package.json, minimark/pnpm-lock.yaml, sub-api/package.json, sub-api/pnpm-lock.yaml, vuex-options/package.json, vuex-options/pnpm-lock.yaml
- :arrow_up: polkadot/packages in minimark
- :arrow_up: polkadot/packages in sub-api
- :arrow_up: polkadot/packages in vuex-options
- :bookmark: vuex-options@0.1.3-rc.0
- :bookmark: sub-api@0.1.1
- :bookmark: minimark@0.1.9-rc.0
=> big polkadot

minipfs/package.json, minipfs/src/cid.ts, minipfs/src/constants.ts, minipfs/src/obtain.ts, minipfs/test/index.test.ts
- :zap: practical tools
- :test_tube: isFullPath
- :bookmark: minipfs@0.3.1-rc.0
=> IPFS MATCHER

minimark/package.json, minimark/pnpm-lock.yaml, sub-api/package.json, sub-api/pnpm-lock.yaml, sub-api/src/Api.ts, sub-api/src/constants.ts, sub-api/src/instantapi.ts, vuex-options/package.json, vuex-options/pnpm-lock.yaml
=> chore: bump polkadot packages

minipfs/package.json, minipfs/src/gateways.ts
- :wrench: filebase gatewayt
- :bookmark: minipfs@0.3.1-rc.1
=> FileBase as IPFS gateway

vuex-options/package.json, vuex-options/src/defaults/endpoints.ts, vuex-options/src/defaults/indexers.ts, vuex-options/src/defaults/prefixes.ts
=> :tada: dot

vuex-options/package.json, vuex-options/src/defaults/endpoints.ts, vuex-options/src/defaults/indexers.ts, vuex-options/src/defaults/prefixes.ts
- :zap: dot && stt
- :bookmark: vuex-options@0.1.5
=> :tada: STATEMINT in Options

metasquid/package.json, metasquid/pnpm-lock.yaml
=> New Squids

minipfs/package.json, minipfs/pnpm-lock.yaml, minipfs/src/magic.ts, minipfs/src/parser.ts, minipfs/src/sanitize.ts, minipfs/src/types.ts
- :tada: initial parsers
- :label: formatter as sanitized output
- :zap: I am parsiiing
- :zap: sanitize JSON and base64
- :bug: do not sanitize nested fields
- :zap: apply formatter when needed
- adds posibility for base64 and json encoding ;):
=> base sixty four

metasquid/package.json, metasquid/src/entity.ts
=> :squid: find by map

minipfs/package.json, minipfs/src/cid.ts, minipfs/src/constants.ts, minipfs/test/index.test.ts, minipfs/test/sanitize.test.ts
- :test_tube: native urls
- :wrench: ipns path
- :bug: format native path urls
- :bookmark: minipfs@0.4.1-rc.0
=> IPFS paths

hyperdata/README.md
=> :memo: :bug: old naming for hyperdata

minipfs/package.json, minipfs/src/gateways.ts
- :wrench: remove r2 gw Close #167
- :bookmark: minipfs@0.4.1-rc.1
Close #167
=> Remove r2 infura gw

minimark/package.json, minimark/pnpm-lock.yaml, minimark/src/rmrk/v2/helper.ts
=> 🔧 destroy collection rmrk2

metasquid/package.json, metasquid/pnpm-lock.yaml
=> :squid: unmet peer deps with sq/ss58 

.github/workflows/publish.minimark.yml
ref https://github.com/kodadot/packages/pull/180#issuecomment-1822446585
=> 🔧 publish minimark workflow

minimark/src/rmrk/v2/types.ts
=> 🔧 DESTROY interaction type

.github/workflows/publish.minimark.yml
https://github.com/kodadot/packages/pull/185#issuecomment-1822719151
=> 🔧 run subfolder workflow

minimark/package.json, minimark/src/rmrk/v2/create.ts
- https://github.com/kodadot/nft-gallery/pull/8395#issuecomment-1838758310
=> 🔧 DESTROY interaction

metasquid/package.json, metasquid/pnpm-lock.yaml, metasquid/src/entity.ts, metasquid/src/types.ts
- :bookmark: metasquid@1.0.0-rc.0
- :arrow_up: Arrow Stick
- :heavy_plus_sign: @subsquid/typeorm-store
- :bug: typeorm should be part of ORM too
- :label: BatchContext
- :boom: entity uses new store
This marks release of Arrow Squid only version for metasquid, please do not use it with lower versions
=> :boom: MetaSquid for Arrow Version

metasquid/src/shared.ts
- :bookmark: metasquid@1.0.0-rc.0
- :arrow_up: Arrow Stick
- :heavy_plus_sign: @subsquid/typeorm-store
- :bug: typeorm should be part of ORM too
- :label: BatchContext
- :boom: entity uses new store
- :bookmark: metasquid@1.0.0-rc.
- :label: :bug: SquidStore can be imported as type
- :rotating_light: toBase[something]
=> [metasquid] 🚨 toBase[something]

hyperdata/package.json
=> :bookmark: hyperdata@0.0.1-rc.4

sub-api/.gitignore, sub-api/package.json, sub-api/pnpm-lock.yaml, sub-api/src/common/extrinsics.ts
- :arrow_up: all deps
- :zap: working fn balance transfer
- :zap: Add balance transfer utility functions
- :see_no_evil: .vscode
- Updated sub-api@0.3.0-rc.0
- @paritytech deprecated https://github.com/paritytech/substrate/blob/master/frame/balances/src/lib.rs#L735
so we will have fun in the repo
=> chore/sub api/remove dust

sub-api/package.json, sub-api/pnpm-lock.yaml, sub-api/test/dummy.ts
- **:test_tube: new KSM RPC**
- **:arrow_up: @polkadot deps**
!!! Breaking - moving Polkadot API to peerDeps
=> chore/sub api/latest

hyperdata/src/types.ts
- https://github.com/kodadot/nft-gallery/pull/11171#discussion_r1839769343
=> feat(hyperdata): `CollectionMetadata` type

minimark/package.json, minimark/pnpm-lock.yaml, sub-api/package.json, sub-api/pnpm-lock.yaml
=> chore: upgrade minimark deps
